# Generated by Django 6.1.1 on 2026-09-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageicon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icon/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Product_image/'),
        ),
    ]
