# Generated by Django 6.1.1 on 2026-09-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(default='OLD_PAYMENT_1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
